config/routes.rb
Pixassistant::Application.routes.draw do

  match 'login' => 'openids#pixnet', :as => :login
  match 'logout' => 'openids#logout', :as => :logout

  match 'home/master' => 'home#master'

  resources :oauth_consumers do
    get "callback", :on => :member
  end

  root :to => "home#index"

  namespace "plugin" do
    resources :banners do
      post "sort", :on => :collection
      get "api", :on => :collection
    end
  end

  namespace "blog" do
    resources :comments do
      post "reply", :on => :member
      post "mark_ham", :on => :member
      post "destroy_batch", :on => :collection
      post "mark_spam_batch", :on => :collection
      post "open_batch", :on => :collection
      post "close_batch", :on => :collection
    end
  end

  resources :assistances

end

app/models/banner.rb
class Banner < ActiveRecord::Base
  belongs_to :user
  acts_as_list :scope => :user

  default_scope order(:position)
end

app/controllers/plugin/banners_controller.rb
class Plugin::BannersController < ApplicationController

  before_filter :login_required, :except => [:api]
  before_filter :check_master, :except => [:api]
  before_filter :store_location, :only => [:index]
  before_filter :find_banner, :only => [:edit, :update, :destroy]

  def index
    @banners = @master.banners
  end

  def sort
    @master.banners.each do |banner|
      banner.position = params[:banner].index(banner.id.to_s) + 1
      banner.save
    end
    clean_cache(@master)
    render :nothing => true
  end

  def api
    user = User.find_by_login(params[:user].to_s)
    unless user.present? && user.banners.present?
      render_json([].to_json)
      return true
    end
    banners = Rails.cache.fetch("banners_#{user.id}", :expires_in => 10.minute) do
      user.banners.select([:position, :image, :url]).to_json
    end
    render_json(banners)
  end

  def new
    @banner = @master.banners.new
  end

  def create
    @banner = @master.banners.build(params[:banner])
    if @banner.save
      clean_cache(@master)
      redirect_to plugin_banners_path
    end
  end

  def edit
  end

  def update
    @banner.update_attributes(params[:banner])
    clean_cache(@master)
    redirect_to plugin_banners_path
  end

  def destroy
    @banner.destroy
    clean_cache(@master)
    redirect_to plugin_banners_path
  end

  protected

  def find_banner
    @banner = @master.banners.find(params[:id])
  end

  def check_master
    unless session[:master].present? #沒設定就直接指定為本人
      @master = current_user
      return true
    end

    master_id = session[:master] || current_user.id
    assistance = Assistance.where(:master_id => master_id).named(current_user.login).first
    if assistance.present? && assistance.perm_blog_comment
      @master = assistance.master
    elsif master_id == current_user.id
      @master = current_user
    else
      flash[:error] = '無權以此人身份執行此動作。'
      redirect_to('/')
    end
  end

  def clean_cache(user)
    Rails.cache.delete("banners_#{user.id}")
  end

  def render_json(json)
    if params[:callback]
      render :js => "#{params[:callback]}(#{json})"
    else
      render :json => json
    end
  end

end

app/views/plugin/banners/_sidepanel.html.erb
  <div id="sidepanel">
    <h2 id="current-panel">外掛</h2>
    <div class="panel-links">
      <div class="panel-selector">
        <%= render :partial => "common/master" %>
      </div>
      <div class="panel-group">
        <h3 id="panel-plugin-blog"><span class="hide">部落格側邊欄位</span></h3>
        <ul class="panel-ul">
          <li class="active"><%= link_to "#{image_tag('//s.pixfs.net/panel/images/icons/layout_header.gif')}Banner連結".html_safe, plugin_banners_path %></li>
        </ul>
      </div>
    </div>
  </div>

app/views/plugin/banners/edit.html.erb
<div id="page-body" class="toolbar-hide">
  <%= render :partial => "sidepanel" %>
  <div id="workspace">
    <div id="breadcrumb">
      <ul>
        <li >
        <span class="crumb">外掛</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li >
        <span class="crumb">部落格</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li >
        <span class="crumb">側邊欄位</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li class="active">
        <span class="crumb">Banner 連結管理</span>
        <span class="raquo">&raquo;</span>
        </li>
      </ul>
    </div><!-- breadcrumb -->
    <div id="function-bar">
      <ul class="action-bar-ul">
        <li class="actions-li">
        <button type="button" onclick="document.location='<%= new_plugin_banner_path %>'">
          <span><img src="//s.pixfs.net/panel/images/icons/add.gif" alt="增加新連結"> 增加新連結</span>
        </button>
        </li>
      </ul>
    </div>
    <div class="content">
      <h3 class="section-header" id="basic-info"><span class="hide">修改Banner連結</span></h3>
      <% form_for(@banner, :url => plugin_banner_path(@banner)) do |f| -%>
        <table class="settings-table th-large" cellspacing="0">
          <tr>
            <th> <label for="banner_image">圖片</label> </th>
            <td>
              <%= image_tag(@banner.image) %><br>
              <%= f.text_field :image, :class => "input-style input-text" %>
            </td>
          </tr>
          <tr>
            <th> <label for="banner_url">連結</label> </th>
            <td><%= f.text_field :url, :class => "input-style input-text" %> </td>
          </tr>
          <tr>
            <th></th>
            <td><%= f.submit :value => "修改" %> </td>
          </tr>
        </table>
      <% end -%>
    </div>
  </div>
</div>
<div id="footer">
  <div id="page-selector" style="float:left;">
  </div>
</div>
<script type="text/javascript">
</script>

app/views/plugin/banners/index.html.erb
<% content_for(:header_js) do %>
  <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.13/jquery-ui.min.js"></script>
<% end %>
<div id="page-body" class="toolbar-hide">
  <%= render :partial => "sidepanel" %>
  <div id="workspace">
    <div id="breadcrumb">
      <ul>
        <li >
        <span class="crumb">外掛</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li >
        <span class="crumb">部落格</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li >
        <span class="crumb">側邊欄位</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li class="active">
        <span class="crumb">Banner 連結管理</span>
        <span class="raquo">&raquo;</span>
        </li>
      </ul>
    </div><!-- breadcrumb -->
    <div id="function-bar">
      <ul class="action-bar-ul">
        <li class="actions-li">
        <button type="button" onclick="document.location='<%= new_plugin_banner_path %>'">
          <span><img src="//s.pixfs.net/panel/images/icons/add.gif" alt="增加新連結"> 增加新連結</span>
        </button>
        </li>
      </ul>
    </div>
    <div class="content">
      <h3 class="section-header" id="basic-info"><span class="hide">Banner連結</span></h3>
      <div class="notice">
        <ul>
          <li>可以直接對圖片拖拉進行排序的動作</li>
        </ul>
      </div>
      <ul id="banners_list">
        <% @banners.each do |banner| %>
          <li id="banner_<%= banner.id %>">
          <%= link_to(image_tag(banner.image), banner.url, :target => "_blank") %>
          <%= link_to('修改', edit_plugin_banner_path(banner)) %>
          <%= link_to('刪除', plugin_banner_path(banner), :method => "delete", :confirm => "你確定嗎") %>
          <li>
        <% end %>
      </ul>
    </div>
  </div>
</div>
<div id="footer">
  <div id="page-selector" style="float:left;">
  </div>
</div>
<script type="text/javascript">
  <!--
  $(function() {
    $('#banners_list').sortable(
      {
        opacity: 0.4,
        update: function() {
          $.ajax({
            type: 'post',
            data: $('#banners_list').sortable('serialize'),
            dataType: 'script',
            complete: function(request) {
              $('#banners_list').effect('highlight');
            },
            url: '<%= sort_plugin_banners_path %>'
          });
        }
      });
  });
  //-->
</script>

app/views/plugin/banners/new.html.erb
<div id="page-body" class="toolbar-hide">
  <%= render :partial => "sidepanel" %>
  <div id="workspace">
    <div id="breadcrumb">
      <ul>
        <li >
        <span class="crumb">外掛</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li >
        <span class="crumb">部落格</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li >
        <span class="crumb">側邊欄位</span>
        <span class="raquo">&raquo;</span>
        </li>
        <li class="active">
        <span class="crumb">Banner 連結管理</span>
        <span class="raquo">&raquo;</span>
        </li>
      </ul>
    </div><!-- breadcrumb -->
    <div id="function-bar">
      <ul class="action-bar-ul">
        <li class="actions-li">
        <button type="button" onclick="document.location='/plugin/banners/new'">
          <span><img src="//s.pixfs.net/panel/images/icons/add.gif" alt="增加新連結"> 增加新連結</span>
        </button>
        </li>
      </ul>
    </div>
    <div class="content">
      <h3 class="section-header" id="basic-info"><span class="hide">新增Banner連結</span></h3>
      <% form_for(@banner, :url => plugin_banners_path) do |f| -%>
        <table class="settings-table th-large" cellspacing="0">
          <tr>
            <th> <label for="banner_image">圖片</label> </th>
            <td><%= f.text_field :image %> </td>
          </tr>
          <tr>
            <th> <label for="banner_url">連結</label> </th>
            <td><%= f.text_field :url %> </td>
          </tr>
          <tr>
            <th></th>
            <td><%= f.submit :value => "新增" %> </td>
          </tr>
        </table>
      <% end -%>
    </div>
  </div>
</div>
<div id="footer">
  <div id="page-selector" style="float:left;">
  </div>
</div>
<script type="text/javascript">
</script>