config/routes.rb
Pixassistant::Application.routes.draw do

  match 'login' => 'openids#pixnet', :as => :login
  match 'logout' => 'openids#logout', :as => :logout

  match 'home/master' => 'home#master'

  resources :oauth_consumers do
    get "callback", :on => :member
  end

  root :to => "home#index"

  namespace "plugin" do
    resources :banners do
      post "sort", :on => :collection
      get "api", :on => :collection
    end
  end

  namespace "blog" do
    resources :comments do
      post "reply", :on => :member
      post "mark_ham", :on => :member
      post "destroy_batch", :on => :collection
      post "mark_spam_batch", :on => :collection
      post "open_batch", :on => :collection
      post "close_batch", :on => :collection
    end
  end

  resources :assistances

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=7" />
    <title>PIXNET 小幫手</title>
    <link rel="stylesheet" type="text/css" href="//s.pixfs.net/panel/css/reset.css" />
    <link rel="stylesheet" type="text/css" href="//s.pixfs.net/panel/css/style.css" />
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <%= yield(:header_js) %>
  </head>
  <body>
    <div id="header">
      <div id="navbar">
        <ul id="user-links">
          <% if current_user %>
            <li><%= link_to "登出 ( #{current_user.login} )", logout_path %></li>
          <% else %>
            <li><%= link_to "登入", login_path %></li>
          <% end %>
        </ul>
      </div>
      <h1 id="home">PIXNET 小幫手</h1>
      <div id="menubar">
        <ul>
          <li><%= link_to "外掛:部落格側邊欄位:Banner連結", plugin_banners_path %></li>
          <li><%= link_to "小幫手設定", assistances_path %></li>
          <li><%= link_to "部落格迴響", blog_comments_path %></li>
          <li><%= link_to "OAuth", oauth_consumer_path("pixnet") %></li>
        </ul>
      </div>
    </div>
    <%= yield %>
<script type="text/javascript">
<!--
$(function() {
  <% if flash[:notice] %>
    alert('注意: <%= flash[:notice] %>');
  <% end %>
  <% if flash[:error] %>
    alert('錯誤: <%= flash[:error] %>');
  <% end %>
});
//-->
</script>
  </body>
</html>